dist: trusty
jdk: oraclejdk8
language: java
services:
- postgresql
- docker
env:
  global:
  - secure: "mLb+goXqMSQevxk+uvwm2uuXZFDs0TopH3arypbK//00cild3euSfvSSxlTi7mrSipsn8zb8jjXtvEtpOfYHmBAcmJ2MUnmgm5GLlyrDUdjyuCqO1Jqf/JuDZUREiTJ8PLe4pZJNVu3QCTHme9IChQEQxXitd2VlIgTAMh/R4ZGhq7iF2gwO6FLsW/pWhAHucxnKtJaHKgBaFeVkKsZgadpATi7W9xUlH2Ip7PqqnLdLwR9Lt46serFGskem2e9NdKZq2ov6DDZTTLcLWOFVomdMvtKev0OIuWlGjhchU1qqdOR1DiAuKZwiqTfis2xtU2OosDxGaP6Ru3Iuz0/o+YVjGDwhbda9XoXeeCv1fzWps0eAvjA+UrmRoP2ISkdw3bdMXn8POIcMO4sYe3Ms8da6nP0F20NaWDxKBliwJdMmLW6AKE6fW3LRF7yTkNB1VJd9QigUwuGMO2Rdp5d2MDg9WhxHwFrnJkAWKBJuG2knjbqEm0DXCYia/XIYGVFXPrw/eUDaechX03mg9qHnjLf0k2Xgp5DCVJ5WKpTa0U8d3AbjgPKB7qej8wSw/rdYWd4zJmsrio//K5nvxmOfA5EaaOM07BRZhkpugczxwyPbSxTLnDUB7vunbX0bzLIrUEdIOnOjNvFXZuNszuon60iB3Jf1kDdbNDftMh5lUF8="
  - secure: "qOaxKQYzbG77Pa0S3Mvnf4p+hpQMSoACs0sb+KsHdMHJoWBZTZ3DjiJ0WZnnNnhLX+zxETX7+dF0bMdPbf0XDGQL2Ga7RIiEs5hxT8sO6+6MisOmlz0aWbN4cz2OAdkS4nkY6rSu1Qd0anZOSyS3om6T2NANJBIPorYe6RC4e5QqUjA54l+BSuJPzcyTVIqxTvKzdYv4wrCNqS3FkcrzfUTOFeV9IbuDO15GMWC6ImxVhJHAntUl6iD77RRQUR/cskFAZ6F1iwVcXQ7KCTwp3naf6GEYKQtMfPJe1ljua6aw3XkwUeRRx/jzlE7XHtRN3R3ZNt6aWAquA/rnN9Li2aH2ZRs+TWzyxT1tJ0wZrguelDjy0Avk9SHL9uSyy7iA6RtSPA3pisGrcVHuHmeVsUa5qZ+SQS6uu9BK0l5SpsRZcgN3hRJvy2aF3fGUoNpuztCCgv503s4URiD2Q3TRJM+6Q/iZP0MoVhLlsRL8DTIshOWXCRktGHb0btr3THctWs+ZaZlaPtm6VuJ2ToLEOcJQwb8T1ir7HlghhtwX85GUN+aL2gcOQjiWFicT3DBxb2RwlN2jdrt+No3xT9EvvcWgx7fbLjhlZFdKcQNgIxOO0wXQR4qpHps16mIc9TtmKDGx7MEVj46tXz+C02QoYVIWAk/Enra8evYqanU46kM="
  - secure: "DcOTHiYDVc0SpqXgqoD0NyBfcoUTulpSPFoC7SfomugH3+oE34GoEtQsRwlB3X/HkNwdWMD1vCOSoRY1vZayzzyKXRieRoM/3BJqY3pIVLbQdnPxc4U/N3ydVk7LncfnTQaVaZ8dhF6lL0AkntVutuKqm5XN8MOJRCOW9FKU7Th6bD99CHFXsBQvzYX5WSeVtQMCV1YQnR4XqCAc9SrwuOQ3qRyuxZtAIjWv2AXo+N7RwW/nTSVsC7UTjhGk2ZuAmoiUKOheLMNwkon4uHzBOkfeIQ6txGJUECQDpd5P67ZS2Cll0wAYm1bet+MaJ3FVwQjkjlN7gEcq8Emr8bzsH8HX80pPGCRtxGQsxTmtJktdI3Ui4iSH7gH/33PrsOi3BQijO5/kiw+R2UTZfDkum6UtC2fXNir4McxiCJr86TyGpRtYIK61MYv1llghwSMSKl5h5BANUb+lMYk0Od8D6jain0ndoOZotPfHGsYsCdNIJ/C1IG6GvL/7hgDoq7LwbEtrM+Og7Dy4Jx+RlNvqtSc3N+3uxT9AlNcdZUhJEcgxFGaeieaMwu3AANAypAaCf6le0sdRaWMWs9i13HGsLFjfI7j+pMHxpX6Cbh2y76B+Tj7Cpu9Cuf+sdkQa3+nwHRxeJEVkoqs9+2hlSnaWSwe9FRsKKgEF2BfAnKM3lU4="
  - COMMIT=${TRAVIS_COMMIT::7}
script:
- "./mvnw clean install -B"
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH";
  fi`
- export IMAGE_NAME=$DOCKER_USER/deliveryservice-docker-image
- docker build -t $IMAGE_NAME:latest .
- docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME:$TAG
deploy:
  provider: heroku
  api_key: "$HEROKU_API_KEY"
  app: deliveryservice1
