dist: trusty
jdk: oraclejdk8
language: java
services:
- postgresql
- docker
script:
- "./mvnw clean install -B"
deploy:
  provider: heroku
  api_key:
    secure: VADiH573sFT3pSyMVOJKFBpAAxlXI0jXPM4ec3icHgztXxBggk79PF1d5ZiOITCVEmx1ILF7Odqk1nZoDj8ZBG42d0ZgBTb8BV8JY0YIqeqUQCzMUtvkGEjsqO/vJpn75zP60bjaFpXzJCrzj0h/6Hdpe5pAkA02Cz4YTvCLLsRV7lX2FlbydDvk6yvfjL39gN+Jd2IFVNnTqMlxO9svK2GsdHmgXuuuEemRGlGUg/Vxlzk7eake0i3PlGhy1WxZ0LzLIMmdVztWgrMH+F7cp2sE8O6fKClPJrVr6mbuO9J2Hj4ebm25cmblKLbsv27hZbhUUPnw8wd/WONM86Asn6ydMLit33cizPf6hwZSh5rJ3KLP7ttLDuNi40tAb1X+0dCAzjC/MiaF3pNNoUDgnQLDMEwkZDCb9WofPS9Jjd3gM9ZBwnPD3TU9Ncmc1qLxf2uFOgjOVjDEzDC6tYmIUNJef56tZ0z+gFC0FfFkUp1A9mVxxpxkYkxZgpbStdfO+Vq0rpEnb6WzUtwj0dbVbxUmitGyg8atK2g7/+thiBXgphfAtKQHJhLgcktB9ymJx9og0FECLGgTayU8oh1fgPpBLMLhXXgwV1iqBC4aT1GWuaP4fvJeDj/hK3awtrqCUzQvwDNSJ8jQi/UiETPWvakQ7TtyKmn6wc3QpEiKyzM=
  app: deliveryservice1
