dist: trusty
jdk: oraclejdk8
language: java
services:
- postgresql
- docker
env:
  global:
  - secure: noY6Om4wG127qb5hIWdN9GU2oNAE3YgvXbWZfG4x12Dk5dhGK3HXTf4PdqZlK+NPXvHaX/hsEW1ZlfiWkN49HDbtBez2+Xwgkhp30R6CZEsLehBU9J0BbAPVBUVEfj9b1KTCsbrv6Uz9lClPT+pjhB0o55ly6X3y+4qGhPIEY+Fb6FgeaDfHV6sFlGAmcH/7cn4ZXVpTkZt3u3j4c/35E5HOI7J9VaQA3u+nIt5afNEKK9lNSYzPtPHGF/NgAjnX79yabCzDpFRtCCgOM/bUXIJkCv0CgHjGqvzwZN5/a+EL9ccy48u7O0KXYdxEvnSM4Rjw1Tu391tM3MZbacL6sn2M/U6TSyYpLaXJnMJBueQSy1mwu6ivqkoUUgK0UcorJZxGKsX8830YuzZ6jzJZZVquGuhn92kNSxQFlV9mH1a4sXjmxxP0RYO4dHaYFXREHKBXnYrCkfNuVtBuWSi7jVsRR04gxlizfu2YL3dq8QD58s3z8/378lAW6szJRtMG81HocB+knULWqg1KSrPwYTSzZMzal9G8imUw6PUszurMua29V7GcaDGduFH5FGaPWYvzSAlXY7nsD1HUHrja9rk4NnFn+WNMefXReJGek/pTYak1zq6LLJhLcwgFre4S6f7j890E9aGrb8stAwOenTdADiJdh7JGkMo14jpJM5c=
  - secure: Su7bsM42+tSSoT9mYV5iqamSXhQc7QTgvF/kZu1BpGEXknGRf7hWEjgdc/xScLXlLnNx2YanYrRcpKpElhMs7Z0+wtVZt9bTEYKRbqefp4Xk9Nd8KAVq150uasg5dTw7LaPwjJglRhIl01edeCWxC5JRiT+2vXdcohqzCUCrYJB0mPDFMOVrP0Oycldut5k9XXWiXrkI0iNISIAQA6Spidz0RzlDjP8EsHCaZTvzXZKZLmet2MTR6pJYK8niIxJvaIQa5V7OEq1vVPsIbqojnt7MoQKOIVstKQtS20HNc9CvbUFGlDUTDEw1ADA576ae4DtBBELZ9hC1kVRzlEB/LytWBtEsD0dsYrCZrraLatGbXmZNL27ubHaJECl/UYaFJCXqv17v5iEPzx/LZ6TSKRUqUj1hAHXlDM1ZL/QzcFH48cpW+KwfSe4k8CH4W9WV76111nI2LiLTtZSYKqBA2BVWwZQ/rotZDa0zR8S2b91v8Hr+8XT40CnOjKQuoF/rArH0WyiLzS4Hncd6iEUlwKwGHUFdeFKDfC5ZsbZpM3yaTwM6lH5jrzJ/VbqRnCimUadgJDJNk9Cbulx9ZxeDD3C6kcbX2F/lPI2WWkI12CrZC2dQbC51r3EwMhEbeiuswSK1Rc/oJCPviAtNqgOv9jSoJoXx41jEKn5eM7coJus=
  - secure: Q4Dk4YIhHH9KsF0j3BbOI5VB5NPNpYW+CFl82BnH6ioNQL6e1nyWq1b4eW8JHuHMc8k9hR+4/ZGWK8FMiD0el+SrYm/Qkrphvfz30EAUjxlCWUq/feI3eWeZaKchscIlrbex7dycREtW3W29f2CYxWSOP8nJOBhkaL9JMiIhza34g3SgeKzXMlOiB/b8eyFXQeAf/2duWjnhC8t74C6YLdR+JiB3MpxMf7C0ewPhrzu3Wb7jN3QtqNv0JUh3VdqEij/Y93umMNszXoePBWdZq2McIdw6UcpwgfUbHxQzCUpyI4OtY8NGTxKdYnq1LiVjFrkeU9zyfU5Y4sDqfgwlLAN8ynP3ydd5EvTJvNcEjm+NKCcVYA0MiI5q31pBXvIYFNSqFWf0yILGLzbMYumETxsf04FXScixIhkJx0FYtJFIyw1mh+uWaOOtjJJbJ8c/Heku31BqSOLuegew8rONVFsk2MN7KY/M5W4W+osCbfmunPiU/hkLDijkUxJk/UsMH+9saXqQde2qwyhEb5j0af3g8v/rc2PlEvsBcL53NZevQYlgOsGjRNIGZn3QUDbRzWHccpJ7UEpvwg0XgPoOxUhatnly8t52rJ/zvTpH97rO4YVYLmmWhpJJIJlOJFi67wuxyZwz8751G+82h+zbQJGvbLPlwhKXHwcQ4w/2Ci0=
  - COMMIT=${TRAVIS_COMMIT::7}
script:
- "./mvnw clean install -B"
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH";
  fi`
- export IMAGE_NAME=$DOCKER_USER/deliveryservice-docker-image
- docker build -t $IMAGE_NAME:latest .
- docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME:$TAG
deploy:
  provider: heroku
  api_key: "$HEROKU_API_KEY"
  app: deliveryservice1
