dist: trusty
jdk: oraclejdk8
language: java
services:
- postgresql
- docker
script:
- "./mvnw clean install -B"
deploy:
  provider: heroku
  api_key:
    secure: RcCqyuVDlzVe9ePP9C0k9PlGQrCW9y6aJrZeZnrDsxVvvXTi46TAu95/I1VWc20AvOgxEOTA5urRup9WIGWYMwQZsE9IxuK+NJBsukFqEkbXZfTmCv1AsD9x9CcPxE4tHId+jmJkHhWlow5thgRub1PoR+XBxkJCY4xXWJHGYb9IM1ihn5HWNa829dSRYSbKGTN9s87o7L/CyqmVjALkBGOnroEBa0wsZbC1Xkf69/Dah6Fbm6WJTTKj1wQIbEfNIp2azVzsRbSe1TOtxxXG8/i/5V6A5hQ55ruQuckK28CoZiclVoqt2s1XlgKBvV4au1jMx20h3JxD3RLRwFu6ktnqYJpG6or/FJYsgfNL1IjNHA6MwemfHXqd2vtOBuYkLUm5agZIDAYpXTsVpgRYNzmxaZ5N6E91KLwyp2ijGXOqXYi8BRdyL1F+2dCMZOnp88uB924Fj5+tt3FzIsBsVchnFzWVl9Cew2hfaHUg2PeMkFdBaCkMdGmPkmNF7vLludmSlHqIhB0VqNIby+x/JQoHXgjrxZVBFGM+eoIsj0s0WKuzl/kuJxJKDQD7CoVGGfcIdnUonalqPzS4L8QtdLDM0f+aKgzU3I7v3CEVBCkJUMtBQZ+OO5xDnqzZMTWo+s6ivoE3FFc5FP4RxEyXtLRlyp9BBeJb7YjH7zjdRNA=
  app: deliveryservice-lab3
