dist: trusty
jdk: oraclejdk8
language: java
services:
  - postgresql
  - docker
env:
  global:
    - secure: "LvR3jz6wvE6WuJgXH52mqKmjMMJqjE+E1mlHktcqTAQRJsqO+MHfOcCeJ3ZWZXTR40QhdPYx2IguuHmIGZqb1SVHC2mb3lOcOqVL1mLQ9C5Q2dmwFm4fmp0STTPTd2r/4iyS7eLMzQn2WSWvxCR/zfz3nZ9Aq5EKh5ZqI+uLl145nKRjtRG4M2k/mc3UI0tPXX42uv1FV2hpWsn4LEQPevdegN9OaUGBMfntHNNRMZKhSlSaPu41+EGEpzfBwN6bfWDZh0LP0fYLVgkKg3a+vnuzggkPYnslDWyciey11jn4L7/7XWfynn6pBEMLk22iCZXWMYl2yFFpPXcPemI3EcJpJDHi2egeCDWHLnTNrh0TOnwpdEtwTQatMGoiKNC/VAf0slL5xSPq/1d6kkNaFGppUyo2qQUuqUSxtMyAOfNj6CwQBU6/wPQNvpgOKx/2LBD7kCz9kne0CVcCnsM5W+ECm8mgl1kSTadbCkS0ZLNSsKsPOGGPrn7+ntMtuPo2pfYjsks2RPZNYdmo9TDeAnNaPp5p7anXRrWiN5cLnF/EHaPUY+3HjB5OvA+e0PhhL8uMYkTTmqjXdhpervpap0BK8e/+rrFk/TjSX3x8xStGAMV4X2gths9uER7QtUox2SSd53IOcBH/2TRvaseZ28PAhH4/1E7y/IxkcqItcbw="
    - secure: "MMJY7FHUG9yXd0iurvpWc098B1jIhSDZUs2+a1wN2lqx6/RIVsBtyjexGscy/QfcKYGVsj81wDLWTZtUPP/5lyu2YtTobECXUZRTkI/D8Q1MD6no0DPkDIaoeEItSf2/Z4YotzHFHAUEE01YI8ee1lU/nw6M/ft6vnXJfRjSr5i4BOWuMWVGZxrzA6Yyvr4stfpRKiQTXCP/RKSVy/i4+4egDqG4XBCGt34WzF+YOCX6zvxhbHFQFPdI+JFEpHyH9ZwUXGGoaCGmoSe3DBAIxSyBbJKqAGsem9RAB9FP7gF7INbvyMkF4IhUgZ9YPvjy4qMHToSgVxaxzD8hZjVBZy8MkM/IGoVU6gGlSiYD8ifh2Du9Lez9DupXxDSx96+t8BuhqDpoT451lX9gElwe8Rl9Gwr2reslVZ2GbPzLZIffn/aKF3exVAEePTOL2epdp5fQI2/4dhsRs/J5LgqhYbHNNiOhSZISglatwdPhnpV8mJF+JUbGk4zs56cUzd4lMlggn38WvtRxh8HR4PmjxDQ0mL85ED99mwEstYKgi9lZXqoB9FaMftN4Ihq4zHwVCbvXyKhkXyzfwM1cE84TVs2GQHGFlPqzHYIPTJLiOTzSZiAw3UG6BHG+jd1ul24IhQA0Bwqub0iGMXSyRlEtUhcBSbCGUBuvnTx9o2TxzJE="
    - secure: "JDT4Vf7FUKfBe66G9gtHvGlyleyvGLseFvCB20mdKMOZfRku9BFETdONTzx1ftgs7ntEv0OOgVElIFIapHGW2WaNIOmy/bqlwugvr6yVo2TAA+yAzrQ0ts37l6zMkYH/rZeN03I+IEv4rErvjhT1NDxwE22YlxR3245HcZ54s0jGSc1Z3EPFfyc+6bXYMzFvwu13fm/zGyp9bkqzjnHpMBvzYv3MQFo6TpPljbx1ddW7AX1fZFq8eZOg8CuOM00ZKiGklvBFxQLE63xkKCz/iUU/MqbT5731+Dzizuqs30wXvPJM7J88O5CPQEWXZMW2bMrbUNyKrZM2hS36GeRphgpVO22wuFL8QYgTdITV64Xy8rF7j4wdJmIVavaNOXMgvhFWjMSmBAicAh4KgPwkI9wjCXZVmOC3p4aobYvuqD+hnywKc7Vw/BdoLrDbnJhRLsVzgxJfnbnOIJTsdczSFz5QHNxm2tDbTGJxqkuHInVabx8ALGwxQf7Bzlwsn4WEv6+L1EYZWAAgyXYaNwh28UbPzFJ8gcLtaAhomoaolO+KA9DmwU4tNJ8dTuOg9OuxNXC+kPQdD5RIjaiRGq77Pnq1GwrL2Nb2gOp/SgmeIp53BhaQX/6x8/jJ0VMWbUQh08Z0Ka/IT3XMZPdlk1J9Wwzwg9xhPihqYvVTMK9Gwu0="
    - COMMIT=${TRAVIS_COMMIT::7}

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
  - export IMAGE_NAME=myapi/my-docker-repo
  - docker build -t $IMAGE_NAME:latest .
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: deliveryservice-lab3


  