dist: trusty
jdk: oraclejdk8
language: java
services:
  - postgresql
  - docker
env:
  global:
    - secure: "CsccKXQzCiKwof8SJO+6cKrINE1DueJwUUZlT/+w8ItjAgIrcjBh8rxoNeRrn335CS7UXh1KoJHJ7jbOdRqGZKj7LVWQ68HZ7GhbSdO+SxhQuNIc3VgijZ6Uu/FG7r0ZS9z9oxqR9wv5UANXoPLO5jxShE+4B2x/je9dLfl4VvTmjzMJrSSRviERjov8+6X+L7hzMNKlAo+7WUudkg/Jh7ZcIs+DU0ppQZueglXHiGlo+uwYV5ig7+0V7hCIo3QpRl0ldmK5LORTsaKppFLjuho6CBV2WqZxlLk7YMIilKS8MvSuYj4Am/KHhgLVk06kk/LLj1i4as9nD/520+57fqdP158XIv8DfKvOhAsE9S0+SbOsh8TWvgsklq45GEcY4PQCsU9hkHhjKIWphln7swqHAKr1H56fg+W1myXPbU4P58kkCd2q/S9nPjZUb1IAbXhE7zBP8TVNdQ0oB34hxPXReZC9I1jS6dIkaqiusWRK4TlMFyKm7IZeLP+jerZxVyIOTK6a0EVF3Shjmuu08PKVCp+VgXNSf8ltRkkWn32rii+MgsZmaM42TKdXL5yjJQ4UnSzz67KbZ37DtX+9QIcb+3Gt73i3GghkAogfly3MdTek1durmi4LECALJ6fz29h2AId598vMPy8rhEZlEXaB28Ykron0l+oDZ3GoJww="
    - secure: "MMJY7FHUG9yXd0iurvpWc098B1jIhSDZUs2+a1wN2lqx6/RIVsBtyjexGscy/QfcKYGVsj81wDLWTZtUPP/5lyu2YtTobECXUZRTkI/D8Q1MD6no0DPkDIaoeEItSf2/Z4YotzHFHAUEE01YI8ee1lU/nw6M/ft6vnXJfRjSr5i4BOWuMWVGZxrzA6Yyvr4stfpRKiQTXCP/RKSVy/i4+4egDqG4XBCGt34WzF+YOCX6zvxhbHFQFPdI+JFEpHyH9ZwUXGGoaCGmoSe3DBAIxSyBbJKqAGsem9RAB9FP7gF7INbvyMkF4IhUgZ9YPvjy4qMHToSgVxaxzD8hZjVBZy8MkM/IGoVU6gGlSiYD8ifh2Du9Lez9DupXxDSx96+t8BuhqDpoT451lX9gElwe8Rl9Gwr2reslVZ2GbPzLZIffn/aKF3exVAEePTOL2epdp5fQI2/4dhsRs/J5LgqhYbHNNiOhSZISglatwdPhnpV8mJF+JUbGk4zs56cUzd4lMlggn38WvtRxh8HR4PmjxDQ0mL85ED99mwEstYKgi9lZXqoB9FaMftN4Ihq4zHwVCbvXyKhkXyzfwM1cE84TVs2GQHGFlPqzHYIPTJLiOTzSZiAw3UG6BHG+jd1ul24IhQA0Bwqub0iGMXSyRlEtUhcBSbCGUBuvnTx9o2TxzJE="
    - secure: "JDT4Vf7FUKfBe66G9gtHvGlyleyvGLseFvCB20mdKMOZfRku9BFETdONTzx1ftgs7ntEv0OOgVElIFIapHGW2WaNIOmy/bqlwugvr6yVo2TAA+yAzrQ0ts37l6zMkYH/rZeN03I+IEv4rErvjhT1NDxwE22YlxR3245HcZ54s0jGSc1Z3EPFfyc+6bXYMzFvwu13fm/zGyp9bkqzjnHpMBvzYv3MQFo6TpPljbx1ddW7AX1fZFq8eZOg8CuOM00ZKiGklvBFxQLE63xkKCz/iUU/MqbT5731+Dzizuqs30wXvPJM7J88O5CPQEWXZMW2bMrbUNyKrZM2hS36GeRphgpVO22wuFL8QYgTdITV64Xy8rF7j4wdJmIVavaNOXMgvhFWjMSmBAicAh4KgPwkI9wjCXZVmOC3p4aobYvuqD+hnywKc7Vw/BdoLrDbnJhRLsVzgxJfnbnOIJTsdczSFz5QHNxm2tDbTGJxqkuHInVabx8ALGwxQf7Bzlwsn4WEv6+L1EYZWAAgyXYaNwh28UbPzFJ8gcLtaAhomoaolO+KA9DmwU4tNJ8dTuOg9OuxNXC+kPQdD5RIjaiRGq77Pnq1GwrL2Nb2gOp/SgmeIp53BhaQX/6x8/jJ0VMWbUQh08Z0Ka/IT3XMZPdlk1J9Wwzwg9xhPihqYvVTMK9Gwu0="
    - COMMIT=${TRAVIS_COMMIT::7}

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
  - export IMAGE_NAME=mtuci-lab/deliveryservice
  - docker build -t $IMAGE_NAME:latest .
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: deliveryservice-lab3


  