dist: trusty
jdk: oraclejdk8
language: java
services:
- postgresql
- docker
script:
- "./mvnw clean install -B"
deploy:
  provider: heroku
  api_key:
    secure: ja2gRQSx3AggukwRbOIpopl/ov1EcYtfrDjTLyajAMNdWkhEOZyoffNG3pEfdgbVVp6VEIInpnibDsu5hMhlx5h38+o/mABLKzTdYBatcqMkPqsdnnPDVThPdnf/ju28hd3Lctx11/LXXlObdnGqrt6Jkq09GJca0lJydOLmCIBRkvmt3lwimFZpICvsxyqXZBmfFGS2d6lgvq5+jmSe9jWt28VCHUhJUUOuuPdAfQwqdL2DIjSAAJL/vzOk8vRcCaz5181W/W9KhnUMKX7uYNDzjg6wQxaq8rYj4OKoTZj91ZXhiDFAILAZGx76xr2jCTeZuI9qPSl+A6irSspF7iTC1T6lHdLrLNx/pQbhDCKHxnEH8PPUk6IztF7mrDbg3lLQ0K4ukSwWPdDk7quAxJmBjWAetQFITkoe61laHdsx3VCJh6fB5Jd+yie/VcV4xKK/3tRWvCGanwmQougwSCiRiTXR+OUMBQiNxMQyGE+b9KX/RepfYeDLVl3IS4Fw9OjhsaeGk/SB04bIEM3avXobCRg0je/OjxiJTBq0NOElBVcls7gYh/S9+AuI8F7kOv2/ulZmwr9VsoISSkaRuo7+oTqSTxuPDQHP64nolvWOZxgLYnoYUd6dvdp97w/sD8duw+z130f50lF91TiYQY2hARKe6ol2hMLuzH+GuyI=
  app: deliveryservice1
