dist: trusty
jdk: oraclejdk8
language: java
services:
  - postgresql
  - docker
env:
  global:
    - secure: "BzH1mnv2YGLDDTMA+pMQL3PYJFu9noLx2NnEGvhaQdUjwfWyGw6CNmk12JKakM0sLdxZZL04NXtY0C7mUerGTBkmzKF4K62gFFbc4h90xDrm1lRpeh/P+xquSIdpHxYPkkJpyFmFsrN4onISJCICM6xj1w/5HsgHZ3qtnSIbbSfYKZvo18mCWidMqy1nJzO+89WE3rLWopuePYc1ICaD7Bp6kLwSrwlU4ZhQF/VQy7iHY7LJuq2UosQ3QO3fLRu9QFXaF9Z8IQU/SEOyU8rFXb1CTGOfNsZ3jxfnb0AgbkagM5E2hQc0CLgoBMHiVM/zz8sG5ijDwhMQ2yYV29qOxf5E7JIVgmsxQk1J27QDIBUGB8aAAPHHUzIS/12qD9jlM0H/Cx3xO3CnV1HJ1rDsElkpkiZg1z4kuhtIG0vR2d8HdB3Ij9RX1LydWPISWALVGNOUUDolCtrvOnO/ZPqhzOMzSMiC2xzyq2IJkXHFU1COMtAmF6fsiFFpEV5MX3zXcujDy9Ea8NtwbdK0z2Pu9KcR9SnV4873NYZH1JeqJWbjcVCRgl0cK/V7IrDebB/6P9WZyZhgcixacAYPwYfQIlyo4+vUmKwbw6etmYcJSgf9Y2tHw+VsTh82d+6EJcYimo9Wg/6nUVXR8p8Kqw30lZAlh25bI7pLSX3X83fQ4o8="
    - secure: "bJNresYuu+nigKke8sEwQLMu7sct3kwfIMOSmnkv/tLS2BlpT3piMm+15rW3tgt+AwkKZkT9xsmXpYMTChCgQ4g8y6DlqK9ebySLvZvtX5w81aMIrNxMmPul20pjbNVUbop6njuPkdSlweIxzI9SVYGeuyTGKZ6hlTbL998gp4aAaUhgimQhXsNjGL11QySH7SvrhTU4aQWg2bqV00GL0r1rppkgrMO3+zKrZ6hlhGXJLnVAH2uJjY4M7z1LgHVtgl9BwdgN4XxMSiCGbxicFXMDgLnfF/43yRzpBmAnZlbLZCvNNvfko7jzVIRPFBXhSF4kHvWOteQkFV57HT6RraxpuLVqCfuS8bD/nxly1gd6lVwpGnbsZ/KR0egVf1Dkdl0aS3w1V1gfhDtUObKcsfLngdEvRy11IYg2xGFt4bib6OXGABKZSwC0c7iAhH06/YI7XGf1OgifXpDnk/O7lMg4+LyBMt2WFDwE6Fr8epc6QKeFuQerXc/YYmfc6nZXEf2wCSKkd0CRWI4G2QO38jB/tVxBSJyzMJK7R6JKw14J98Mcg5djQVMKOdb9/qNJimc4Xh+SYLbJgmIwfdqLR/QNJdvHBSsafrmW0cur44S+YMbFFH3BfbdmpXryU66TWX+3bMgDAhepKHbuZ6W82QVste3vvUa8lnYRwJWyqyc="
    - secure: "d6tQIz9+xXWT6d98oL2ip3H34EWTMXuFQbhxWv8eQaIWkd/y9yYSEBhdVJLUpTSgMYZMq7M/IE7WiE4j0GuGaW+Hfkjto9zqPgHRqghmJe5J5ocxegsW2ym+VYeDvEuz+FikB8MR7BxTIBcrCMa6tUWvPIIpy47kkacYuMGeheyBzkdzDbjb2N7jl40Ur/3qFAdi47EB1DTDVXIJ2SRGX3dofwLh3QARdBa7fKOZ5W3P2KZufRocUZHDelJDZ+K2JpXQNDz/4AeK8DWryMeBwLpHWSEdXYweoHDuMrF9fuS5Mo/i+VyHPWfh4yPkhciIyWBxVhwjRJAW0Nyn2AW0HjjDlKsHR74oE9oNs4rNWIB0Z/DlI0R6NsinIakdPVyYVusnVmUkn7Ykl5Xfq61zY8JOI1D0+eUo8olKT7FvnIuhlZKPfMz41D7fpDpTaM+PfhhaV9SlAXFfmud21kttvorfLZwQQ1JtgVaSmEmEKxBktYWJ9xBS9odRnv18SNc5PUkEus5evKexMsJmHcSRxUmU/sp81NMkCSkE3oOwp3Eoyy5OzB9tbC7bPaJrQOW+ZxWAS5zf3d2s6C0QVRd5WNA/6OEBjDBj9s85IXIiy8tQtJIl2PDhEXKminqIXnnlGjdBff++OT8F90VHxvPyM16OQAY6ijawIUyfKnYN13o="
    - COMMIT=${TRAVIS_COMMIT::7}

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
  - export IMAGE_NAME=muxache/deliveryservice
  - docker build -t $IMAGE_NAME:latest .
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: deliveryservice1