dist: trusty
jdk: oraclejdk8
language: java
services:
- postgresql
- docker
script:
- "./mvnw clean install -B"
deploy:
  provider: heroku
  api_key:
    secure: kYcfbGMrV4Gt3OQqCFvozzrY4jPLmEEJPjSmsgQgP2uJx0LSuw2Prr9yAg0Ayku1amRcBQOiXP9Wk0SF6bwyLvevWGxi7GBrbqICwHaG/JPFHvgKLsiZjaMfT5ZqUmWQ5yMs+wVf1T0+i068/ckG4T3xw8ONlwZdZei84xzwNoLKBbhmMvxZ83GDBR91gR1/C8s1GIQnypbEYFwZk9NCzb7XAAon+0y7YmuRfoARFdbRREWI0lTuNLQmh6lMz/0H4X5dgPE/OtZ3iwGLptNZxYZNmO/GREGK+HWRMMB7gzQ71MeawCvNrCfOKVMQHnwp8lUtg0LxrglJAVZEFD9Nliiw6YrjfKjqeFywKLlm8POLDSscsMk3QCFNwuTaGbl1yOnD+gxLeEUhmK4BB7w1/wXASu0VQ8R3bG1ZigEmO5Z+OeYNwIkUrteTkI8laUvYtLZBpegZfeAFNQDghyhasFiLwvClU3gHk6a8a3+eagnS0tk+y4DgSIyxwy+yL3E+QgkJe/RfL5zCvLIYLT4q7NFrSL27VPHXYzTgPjsEh4npV3dCRXNLGMUhUprGIL+77khTmDo/WrsftkgnwlVv5E9lU6mD7ApVGd8pTpDSUuxQ1YJK4g631YocMajMJErhMNeg3gO5T1JVkEzoefm1hzAocV7kC+EVaBnZKZNLpso=
  app: deliveryservice1
