dist: trusty
jdk: oraclejdk8
language: java
services:
- postgresql
- docker
script:
- "./mvnw clean install -B"
deploy:
  provider: heroku
  api_key:
    secure: i0JCs54EgwTSzT+0nPQ7AFaBraPNj5+TRgMLUz6UJ+G1Ipd/agji3vJffVbRkkWIE0/mlXr0qlGziCexo/6YR1ZvNo5cXUKes95lMYP0654mQ8v797kkefYqivS4yDht5hY/NcPU1S1/VseFVfEXZEoulgXEscwcnamuVbRA5Y9x2gE4J9+CeNo4t1aUwhgIZkBQapua2cWRajg4+wXOmMj8jJXZyjdwB/+i1Bj5BU2FBOHwJIKrFL7+ZnUVs3pEfF4cs4IP1MK01ocA5DPxfTWh2wmulFvRk8hELmGKNZvYAeXEVN7FBRS6LvOGOQCnzT1e0QpT07pg+jHzO+DERta3RFOAbzmWxc2wHZUDKGpeg2/rWZgSicedqnBenpYQP2Fu0rJuMWMkywu2Q9GzyqsFER1LyKNmvFRcRSJAKSYdT1D95rxrke0N7aFz8d7z5Gj6oLCg22Jhgi9m4fm2myhdFk+FPx4QKX4duN6Y2xs/3BhZVqrrKARtglhC7AZhF9poH6A1Z88GVugQp7StS8v04MWf2n053x4xSBeX7qFeVXB1l7X677txAK7s5IxXNqGYvBTHewvD8mOnmQuw35UwlpL0tVqZ+0+afcBnJ7HSqNpRKWuLehOJfYRhvkeHHMOvFipElVG3CknZk/g6iJ4v/85yyF2L9eI59CHSC+o=
  app: deliveryservice1
