dist: trusty
jdk: oraclejdk8
language: java
services:
- postgresql
- docker
script:
- "./mvnw clean install -B"
deploy:
  provider: heroku
  api_key:
    secure: N3sXzNNOZeJNuiN80ib3AquPV82smfTX+U2p+F+ZNAD2HaI8do/zHXqloWXLLdPjZ9E0vC+BXItF13d3lvrKrWPSLo9mARaF+1DRP1iHsRHorpJwYCR5NYT4zWe4JMOZJKHq0B+f96aU5NOhray3shtL/mGtK/ahKIZLFnM8eG5QWsn70UjxMetIHqfO1Fvb5fxLpN0Iy7f+XaNzQ4ET8ugR1aZfL2GzM+0YpX6EhB5bMC6g2fiwwXxPjV+qsVuyeK2P8VO2S5jf3Z10k/ZBIqRAdCLEEI8cQ4SPfj/J9GVxxOXoFqvX1rKH2SG4XWpZtupLPlzix2o18GQjhdjMQoj4WGQVOdVA14ViEhSqVhSCxGHDGEvz5yPz9isAMCpGCarLQ9dDJTjqrX2alI+z9wIRTS2Neuo6ZYVRdA+/wGTY9JbbuA31pxnRR5xdvwJCM6Js3bTEAIEydzp5WtsXtXS1LT7tVR565JgkUY0Kdkgy4xcjx/U/Qdt2suxQ/ijlGvXFqw2eCfImoB1AtTleDg2HgkGUt38XK+dl6gZuil3ahyyxChwhX9yDQfVszwfB9i8aO2kUiotYSakGRJijbQnk6gHGR/JXyEPUq1I4gmX4wkktYhN+dZ37e45OaafmAs6NvsuCHhPMql1m+61grWU+tQRqFP3Ug9UIlxy3EY4=
  app: deliveryservice1
