apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: deliveryservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deliveryservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deliveryservice
    spec:
    containers:
      - image: myapi:latest
        imagePullPolicy: Never
        name: myapi
        ports:
        - containerPort: 8099