apiVersion: v1
kind: Service
metadata:
  name: deliveryservice
spec:
  type: NodePort
  ports:
    - nodePort: 31317
      port: 8099
      protocol: TCP
      targetPort: 8099
  selector:
    app: deliveryservice